# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/timing_def.xdc

# Block Designs: bd/design_1_conversion/design_1_conversion.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_conversion || ORIG_REF_NAME==design_1_conversion} -quiet] -quiet

# IP: bd/design_1_conversion/ip/design_1_conversion_width_conv_AI_0_0/design_1_conversion_width_conv_AI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_conversion_width_conv_AI_0_0 || ORIG_REF_NAME==design_1_conversion_width_conv_AI_0_0} -quiet] -quiet

# IP: bd/design_1_conversion/ip/design_1_conversion_fifo_generator_0_0/design_1_conversion_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_conversion_fifo_generator_0_0 || ORIG_REF_NAME==design_1_conversion_fifo_generator_0_0} -quiet] -quiet

# IP: bd/design_1_conversion/ip/design_1_conversion_xlconstant_1_0/design_1_conversion_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_conversion_xlconstant_1_0 || ORIG_REF_NAME==design_1_conversion_xlconstant_1_0} -quiet] -quiet

# XDC: bd/design_1_conversion/design_1_conversion_ooc.xdc
