@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Aug 24 21:16:59 +0330 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim design_1_conversion_wrapper_tb_behav -key {Behavioral:sim_1:Functional:design_1_conversion_wrapper_tb} -tclbatch design_1_conversion_wrapper_tb.tcl -protoinst "protoinst_files/design_1_conversion.protoinst" -log simulate.log"
call xsim  design_1_conversion_wrapper_tb_behav -key {Behavioral:sim_1:Functional:design_1_conversion_wrapper_tb} -tclbatch design_1_conversion_wrapper_tb.tcl -protoinst "protoinst_files/design_1_conversion.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
